### ISSUE TITLE
The main anchor can't receive message from anchor C.

### ISSUE THREAD

**Issue by Elon-Wang** [F-Army/arduino-dw1000-ng#128]
To begin with, I use the Arduino UNO R3. and use 5V to supply the DW1000 chips.

The situation is that, main anchor can range with the tag, and so does the anchor B, so main anchor can receive the ranging report from anchor B.

However, main anchor can't receive message from anchor C, even I tried to use different DW1000 chips to have the test, the main anchor still can't find anchor C. So, this might not be a hardware problem.

**Comment by Elon-Wang** [comment]
Try to print out the message on tag, and found it only receive the message from anchor B for once, seem like it doesn't receive the ranging confirm message. But the main anchor can receive the ranging report message, and anchor B can print out the ranging result.

![photo_2018-10-24_23-17-21](https://user-images.githubusercontent.com/31354867/47446773-877b6780-d7ee-11e8-83e7-6c0a263a65c9.jpg)

**Comment by Elon-Wang** [comment]
The problem can be solved by add a delay between the transmitActivityFinished() and transmitRangeReport() these two method like this,

![tim 20181025004929](https://user-images.githubusercontent.com/31354867/47447353-dfff3480-d7ef-11e8-8c72-fd3c0f5dd1f4.jpg)


The reason is that if you sending the message from MCU to DW1000 chip too frequently, this might cause a problem.
When the chip is dealing with the old message when you send in a new message to the chip, it will lost the first message and only send out the second messages, so main anchor can receive ranging report but tag can't receive ranging confirm.

**Comment by Sonic0** [comment]
I think that this Issue should be closed. Fixed with #127

**Comment by Elon-Wang** [comment]
Yeah, thank you for reminding。
