### ISSUE TITLE
Example TwoWayRanging is not work.

### ISSUE THREAD

**Issue by tdh8316** [F-Army/arduino-dw1000-ng#139]
### Step 1: What do you want?
* TwoWayRangingInitiator and TwoWayRangingResponder do not work. therefore I want them to work.

### Step 2: Describe your environment
 * Arduino IDE version or Toolchain: Arduino IDE 1.8.7
 * Arduino device: Arduino Uno R3
 * Used adapter board: None
  
#### Affected file(s) or example(s):
  * TwoWayRangingResponder.ino
  * TwoWayRangingInitiator.ino

#### Observed Results:
![twowayranging-failed](https://user-images.githubusercontent.com/20598077/51664313-87148780-1ffc-11e9-8a98-65f8e7663c93.png)
It seems not to work!

Thus I tried Basic Connectivity Test.
![basicconnectivitytest](https://user-images.githubusercontent.com/20598077/51664512-e2467a00-1ffc-11e9-849a-4fbf5018855d.png)
I'm not sure it's correct output because I'm a beginner of Arduino and DWM1000.
But I don't think there is any noticeable problem.

And then I uploaded Basic Sender/Receiver to Arduino.
![basic-sender-receiver](https://user-images.githubusercontent.com/20598077/51664703-5c76fe80-1ffd-11e9-9f69-cdf09d6ed723.png)

I still have no clue about this, but it seems to work fine.

>EDIT: [thotro/arduino-dw1000](https://github.com/thotro/arduino-dw1000)
I tried also thotro's library.
![thotro](https://user-images.githubusercontent.com/20598077/51667393-57b54900-2003-11e9-9f5f-09e230d14e98.png)
The device is removed immediately after it is added.

Why are BasicSender and Receiver working but TwoWayRanging not working?

#### Expected Results:

  * Jaja, I expected they work.

# Wiring
![wire](https://user-images.githubusercontent.com/20598077/51665725-c8f2fd00-1fff-11e9-835f-a2c2ff6ee0ac.png)
![real](https://user-images.githubusercontent.com/20598077/51665733-d01a0b00-1fff-11e9-8784-92a8085af96c.jpg)

**Comment by tdh8316** [comment]
Add a wiring diagram

**Comment by tdh8316** [comment]
This turns out to be a hardware problem.

**Comment by tdh8316** [comment]
Completely resolved after adding a 10K pull-up resistor according to [this datasheet](https://www.decawave.com/wp-content/uploads/2018/09/dwm1000-datasheet-1.pdf).

**Comment by Leylan24** [comment]
Where did you put the 10K resistor ? I am having the same issue my Basic Receiver and Basic Sender is working but the Two Way Ranging example doesnt work

**Comment by tdh8316** [comment]
@lgr9603

**Comment by Sonic0** [comment]
> Where did you put the 10K resistor ? I am having the same issue my Basic Receiver and Basic Sender is working but the Two Way Ranging example doesnt work

I think that the @tdh8316 's solution is relative to section 5.2.2 inside DWM1000 datasheet

**Comment by lgr9603** [comment]
@Leylan24 I'm a coworker of @tdh8316 .
Well, we put the 10K resistor on pin 2 to remove noises flowing through it.
And drop the voltage of digital pins from 5V to 3.3V. Dwm1000 can work between 2.4V and 3.75V. (Along to datasheet on decawaver.com)
As I said, arduino uno digital pins use 5V, but DWM1000 sends output signals in 3.3V. So we should increase voltage of DWM1000 signal from 3.3V to 5V. 
![describing_PICTURE](https://user-images.githubusercontent.com/34643883/64489588-0c009880-d290-11e9-8fd9-0c45ff72543f.png)
This is how we worked. I hope it can be help.

**Comment by Leylan24** [comment]
Thanks for you reply. I'm using the ESP8266 Nodemcu and get very inaccurate ranges no idea why

**Comment by Leylan24** [comment]
This is a bit of a stupid question.

But does the ranges only print when the IRQ pin gets pulled high?

**Comment by Sonic0** [comment]
> This is a bit of a stupid question.
> 
> But does the ranges only print when the IRQ pin gets pulled high?

With this library, the IRQ pin is not required. There are two different init processes, with or without Interrupt pin.
