### ISSUE TITLE
Anchors send their address if they receive a ping from Tag ?

### ISSUE THREAD

**Issue by asheeshraikwar** [F-Army/arduino-dw1000-ng#154]
I want to send a ping message from Tag to the Anchors present in the coverage area and in response, they send their addresses to the Tag, How can I achieve this?

**Comment by Sonic0** [comment]
Or you should make your own payload, write this inside buffer registry and send it. To the other side read the buffer, parse payload and send a response.
This is the same operation that you must do with the RTLS standard, but the standard's payloads are recognized by all RTLS devices(that implement it).

**Comment by asheeshraikwar** [comment]
Hi, thank you for your response... Anchor Main gets ranges between Anchor B, C, and Tag. I assume two cases here which one is correct or any other possibility.
![Anchor_Main _COM_Port](https://user-images.githubusercontent.com/47691342/67139558-3a01d100-f26f-11e9-9a0b-3700a6577f23.png)

Case 1. Is Anchor B and C sending their Range from Tag to Anchor Main?
Case 2. Or Tag sending Ranges from Anchor B and C to Anchor Main?

**Comment by Sonic0** [comment]
The right case is the Case 1.
