### ISSUE TITLE
Where is Mannual

### ISSUE THREAD

**Issue by asheeshraikwar** [F-Army/arduino-dw1000-ng#162]
I am looking for DW1000Ng user manual can you please point me toward it.
![2019-12-04](https://user-images.githubusercontent.com/47691342/70117132-a2273d80-168a-11ea-8898-3e59d0bd4476.png)

**Comment by Sonic0** [comment]
In [WiKi](https://github.com/F-Army/arduino-dw1000-ng/wiki/Decawave's-documentation) there are all links.

**Comment by asheeshraikwar** [comment]
Hi thanks for the response, there is any function that gives the tag address from which Anchors ranging?

**Comment by Sonic0** [comment]
We are going to answer you as soon as possible to all issues (me or @an4cr0n ).

**Comment by asheeshraikwar** [comment]
Thanks, I am really stuck on this.
![Untitled](https://user-images.githubusercontent.com/47691342/70129478-cee84e80-16a4-11ea-9ad1-1e47b841e135.png)

**Comment by anacromaniac** [comment]
@asheeshraikwar i replied to you in the other issue, i will close this one!
