### ISSUE TITLE
How many tags support working at the same time？

### ISSUE THREAD

**Issue by PeterSun01** [F-Army/arduino-dw1000-ng#166]
### Step 1: What do you want?

* Report an issue.
* Improve code (and need help).
* Suggest a new feature.
* Present a new hardware adapter board or wiring.
* Want to report my experience or measurement. (Please also add them to the wiki!)

### Step 2: Describe your environment

 * Arduino IDE version or Toolchain: _____
 * dw1000ng Library version: _____
 * Arduino device: _____
 * Used adapter board: _____
  
#### Affected file(s) or example(s):
  * Filename 1
  * Filename 2

#### Steps to reproduce (for bugs only):

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

#### Expected Results:

  * What did you expect to happen?

#### Relevant Code:

```c++
  // TODO(you): code here to reproduce the problem
```

**Comment by Sonic0** [comment]
At the same time, you can perform Two-Way-Ranging with only one Tag.
See [APS013](https://www.decawave.com/wp-content/uploads/2018/10/APS013_The-Implementation-of-Two-Way-Ranging-with-the-DW1000_v2.3.pdf) for more information about TWR.

**Comment by PeterSun01** [comment]
> At the same time, you can perform Two-Way-Ranging with only one Tag.
> See [APS013](https://www.decawave.com/wp-content/uploads/2018/10/APS013_The-Implementation-of-Two-Way-Ranging-with-the-DW1000_v2.3.pdf) for more information about TWR.

Think you so much!
I konw 1 slot =1 tag
so  how many slots this demo (StandardRTLSAnchorMain_TWR.ino)support？
For example, there are 2 tags to send blink messages， Does the AnchorMain assign two slots to them？

**Comment by anacromaniac** [comment]
No, for the examples we just made devices communicate with each other on a best effort way, there are no real timed slots but rather some hardcoded pause we found empirically when testing on the devices.
Feel free to post a pull request if you manage to write an example with such feature!

**Comment by jack-vn** [comment]
hi @Sonic0 , Can you support me ? I can add more tag (2-10) with this library . 
I'm using Arduino mini + DWM1000
