### ISSUE TITLE
How to add more tag ??? thanks you

### ISSUE THREAD

**Issue by jack-vn** [F-Army/arduino-dw1000-ng#169]
### Step 1: What do you want?

* Report an issue.

**Comment by Sonic0** [comment]
Hi @jack-vn , look at these other issues:
#166 --> How many tags support working at the same time
#160 --> Multi tag support
#161 --> Printing of Tag Address on Anchor Main

**Comment by Sonic0** [comment]
Very quickly:

> The simplest way would be to add a pause after every transmission to not have multiple tag talk on top of the other with the anchor. (or better deep sleep, which is indipendent of multi or single tag)

Issue #160 is the most important. Based on the above message from @0nism , You should insert the delay in each TAG, in this way the "Blink" transmissions frame isn't going to occur at the same time.
