### ISSUE TITLE
hey everyboby! i want to using TDoA algrithm for indoor tracking system. But i have problem about SYNC anchors and a TDoA library for arduino.  

### ISSUE THREAD

**Issue by jack-vn** [F-Army/arduino-dw1000-ng#175]
### Step 1: What do you want?

* Report an issue.
* Improve code (and need help).
* Suggest a new feature.
* Present a new hardware adapter board or wiring.
* Want to report my experience or measurement. (Please also add them to the wiki!)

### Step 2: Describe your environment

 * Arduino IDE version or Toolchain: _____
 * dw1000ng Library version: _____
 * Arduino device: _____
 * Used adapter board: _____
  
#### Affected file(s) or example(s):
  * Filename 1
  * Filename 2

#### Steps to reproduce (for bugs only):

  1. _____
  2. _____
  3. _____

#### Observed Results:

  * What happened?  This could be a description, log output, etc.

#### Expected Results:

  * What did you expect to happen?

#### Relevant Code:

```c++
  // TODO(you): code here to reproduce the problem
```

**Comment by anacromaniac** [comment]
You need custom hardware with dw1000 you can't use dwm1000. For more specific details refer to the official chip documentation files.
