### ISSUE TITLE
Save antenna delay in EEPROM breaks compatibility with ARM based MCU's

### ISSUE THREAD

**Issue by Brezensalzer** [F-Army/arduino-dw1000-ng#183]
Hi,

commit 4309849 breaks this library with all ARM based MCU's as they don't have an EEPROM.
In my case it won't compile for an Adafruit Feather M0 board:

/libraries/arduino-dw1000-ng/src/DW1000Ng.cpp:48:10: fatal error: EEPROM.h: No such file or directory
   48 | #include <EEPROM.h>
      |          ^~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Adafruit Feather M0.

Please make this code (4309849) platform dependant.

Best Regards
Stefan

**Comment by anacromaniac** [comment]
Thank you so much for this report and also the pull request, we will review it as soon as possible!

**Comment by Sonic0** [comment]
I confirm that changes made by @Brezensalzer works on Arduino's AVR boards like Pro mini and Uno.

**Comment by Sonic0** [comment]
PR #184 merged.
