### ISSUE TITLE
TDoA Update ? 

### ISSUE THREAD

**Issue by metehanemlik** [F-Army/arduino-dw1000-ng#194]
Hi, 

TDoA is a superior technology than TWR. I think we should do TDoA instead of TWR. Will you plan to make TDoA in the future?

**Comment by Sonic0** [comment]
Hi @metehanemlik,
Yes, TDoA is a superior technology than TWR. 
However, in TDOA approach the biggest problem is the clocks sync and DWM1000 is not the best hardware to do this. DWM1000 hasn't an external pin to inject the clock. One possibility is wireless clock sync but complicated. Examples and RTLS libraries of this project have been made only for TWR.
A few additional information in closed issue #142
