### ISSUE TITLE
analogRead() for ADC1 conflict

### ISSUE THREAD

**Issue by elgranshaman** [F-Army/arduino-dw1000-ng#197]
### Step 1: What do you want?

* Report an issue.

### Step 2: Describe your environment
Arduino IDE

 * Arduino IDE version or Toolchain: 1.8.13
 * dw1000ng Library version: v0.3
 * Arduino device: ESP32
 * Used adapter board: custom device
  
### Step 3: Describe the problem
When loading one custom board with the tag example, and another with the anchor example, the anchor board stops the serial output from the two way ranging loop when the function analogRead() is called. Only happens for ADC1. TWR can start again if the initialization code is repeated.

**Comment by anacromaniac** [comment]
Thank you for the report! Can you provide more details?

**Comment by elgranshaman** [comment]
Hello,

I am using the code from examples TwoWayRangingInitiator.ino and TwoWayRangingResponder.ino

On the responder example main loop, I have added the line analogRead(36). 

Calling this function which uses peripheral ADC1 stops the TWR function.

If I comment this line, I can see the expected output on the serial monitor of the distance between the two modules. However, if I call this function, there is not serial output anymore.

Only happens for ADC1, if I change to a pin from ADC2, then it works fine.

**Comment by Sonic0** [comment]
Hi @elgranshaman, Are you using the latest code from Master branch?

**Comment by elgranshaman** [comment]
Hello,

Just downloaded the latest master branch and it's fixed! Thanks a lot and sorry to distrub you
