### ISSUE TITLE
getPrintableDeviceMode function prints data from class and not from device

### ISSUE THREAD

**Issue by anacromaniac** [F-Army/arduino-dw1000-ng#26]
This is bad as a bad configuration can slip away to someone not aware of this behavior.
Data should instead be read from device using readBytes

**Comment by Sonic0** [comment]
![What](https://media.giphy.com/media/fpXxIjftmkk9y/giphy.gif)

**Comment by Sonic0** [comment]
@an4cr0n  what do you think about this refactor?
