### ISSUE TITLE
Datarate at 110 Kbps with 4096 preamble length doesn't work.

### ISSUE THREAD

**Issue by anacromaniac** [F-Army/arduino-dw1000-ng#28]
//static constexpr byte MODE_LONGRANGE_LOWPRF_LONGPREAMBLE[] = {TRX_RATE_110KBPS, TX_PULSE_FREQ_16MHZ, TX_PREAMBLE_LEN_4096};
//static constexpr byte MODE_LONGRANGE_HIGHPRF_LONGPREAMBLE[] = {TRX_RATE_110KBPS, TX_PULSE_FREQ_64MHZ, TX_PREAMBLE_LEN_4096};

They should be settable but a bug makes the device not work, so they are commented while working at this problem.

**Comment by Sonic0** [comment]
As you said the problem is the too much short delay in every Arduino example Sketches.
3 mS is not a valid delay for 4096 preamble length. I tried 5 mS and now work very well.

**Comment by Sonic0** [comment]
The minimum delay is ~4900 uS
